version: '3.4'

services:
    node:
      build: .
      restart: always
      ports:
        - ${PORT}:${PORT}
      volumes:
        - ./logs:/usr/src/app/logs
        - ./src:/usr/src/app/src
      depends_on:
        - postgres
      environment:
        - PORT=4000
      networks:
        - my-net
    postgres:
      build: ./database/
      restart: always
      networks:
        - my-net
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}

networks:
  my-net:
    driver: bridge