version: '3.4'

services:
    node:
      build: .
      restart: on-failure
      ports:
        - ${PORT}:${PORT}
      volumes:
        - ./logs:/usr/src/logs
        - ./src:/usr/src/src
      depends_on:
        - postgres
      environment:
        - PORT=${PORT}
      networks:
        - my-net
    postgres:
      build: ./database/
      restart: on-failure
      networks:
        - my-net
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      volumes:
        # - ./database:/usr/src/app/database
        - ./database:/var/lib/postgresql/data
      environment: 
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: ${PGDATA}

networks:
  my-net:
    driver: bridge