version: '3.4'

services: 
  node:
    build: .
    ports: 
      - ${PORT}:${PORT}
    env_file: 
      - .env
    volumes: 
      - ./logs:/usr/src/logs
      - ./src:/usr/src/src
    networks:
      - my-net
    environment: 
      - PORT=${PORT}
    depends_on: 
      - postgres
    restart: always

  postgres:
    build: ./database/
    env_file: 
      - .env
    networks:
      - my-net
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST_DOCKER}
    restart: always

    # pgadmin:
    #   image: dpage/pgadmin4
    #   restart: always
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
    #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    #   ports:
    #     - "5050:80"
    #   volumes:
    #     - pgadmin:/var/lib/pgadmin
    #   depends_on:
    #     - postgres
    #   networks:
    #     - my-net

networks: 
  my-net:
    driver: bridge

volumes: 
  pgdata:
  # pgadmin: